export enum PRODUCT_IDS {
  DEVELOPER_INSURANCE = 'dev_insurance',
  DESIGNER_INSURANCE = 'designer_insurance',
}

export enum PURCHASE_STEPS {
  EMAIL = 'email',
  AGE = 'age',
  NAME = 'name',
  SUMMARY = 'summary',
}

export const DEVELOPER_PURCHASE_STEPS: PURCHASE_STEPS[] = [
  PURCHASE_STEPS.EMAIL,
  PURCHASE_STEPS.AGE,
  PURCHASE_STEPS.SUMMARY,
]
export const DESIGNER_PURCHASE_STEPS: PURCHASE_STEPS[] = [
  PURCHASE_STEPS.EMAIL,
  PURCHASE_STEPS.AGE,
  PURCHASE_STEPS.NAME,
  PURCHASE_STEPS.SUMMARY,
]
